tickrate_secs = 5
max_errors = 20

env_filters = [
  "storage_bus=info",
  "supervisor=info",
  "amplifier_ingester=info",
  "amplifier_subscriber=info",
]

[telemetry]
otlp_endpoint = "http://localhost:4317"
otlp_transport = "grpc"

[nats]
urls = ["nats://localhost:4222"]

[gcp]
redis_connection = "redis://127.0.0.1/"
tasks_topic = "amplifier-tasks"
tasks_subscription = "amplifier-tasks-sub"
events_topic = "amplifier-events"
events_subscription = "amplifier-events-sub"
ack_deadline_secs = 10

# tls key for amplifier api secured by gcp kms
[gcp.kms]
project_id = "axelar-relayer"
location = "global"
keyring = "amplifier_api_keyring"
cryptokey = "amplifier_api_signing_key"

[amplifier_component]
# pem format cert
tls_public_certificate = '''
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
'''
# NOTE: DEVELOPMENT ONLY
# cert + private key
# pem format cert
identity = '''
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
'''
url = "https://amplifier-devnet-amplifier.devnet.axelar.dev/"
chain = "" # NOTE: Your chain name in axelar
get_chains_limit = 100
invalid_healthchecks_before_shutdown = 100

[health_check_server]
port = 8080
